### ISSUE TITLE
Commands Bug

### ISSUE THREAD

**Issue by LuxZ** [FabioZumbi12/PixelVip-Spigot#2]
I recently used your plugin and I encountered an error trying to activate the vip with the code using /usekey
 
Vault Used: 1.5.6
Spigot: 1.8.8
 
Spigot Log:
 
[21:52:29] [Server thread/INFO]: Migu issued server command: /usekey J4LJTVMAR1
[21:52:29] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'usekey' in plugin PixelVip v1.0.4
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
at br.net.fabiozumbi12.PixelVip.PermsAPI.getGroup(PermsAPI.java:16) ~[?:?]
at br.net.fabiozumbi12.PixelVip.PVConfig.enableVip(PVConfig.java:315) ~[?:?]
at br.net.fabiozumbi12.PixelVip.PVConfig.activateVip(PVConfig.java:285) ~[?:?]
at br.net.fabiozumbi12.PixelVip.cmds.PVCommands.useKey(PVCommands.java:351) ~[?:?]
at br.net.fabiozumbi12.PixelVip.cmds.PVCommands.onCommand(PVCommands.java:83) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
... 15 more

**Comment by FabioZumbi12** [comment]
This is the error: 

> Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.

Seems your vault dont loaded property or you have wrong group configurations.

**Comment by LuxZ** [comment]
Vault loaded correctly and I use PEX for group, so I do not know what could be ...
I testing with vault 1.5.5 and same problem.

**Comment by LuxZ** [comment]
Fixed, was a corrupt plugin. Awesome plugin!
